#define KB_CATEGORY_CLIENT "Client"
#define KB_CATEGORY_COMMUNICATION "Communication"
#define KB_CATEGORY_MOVEMENT "Movement"
#define KB_CATEGORY_MOB "General Mob"
#define KB_CATEGORY_LIVING "Living Mob"
#define KB_CATEGORY_CARBON "Carbon Mob"
#define KB_CATEGORY_HUMAN "Human Mob"
#define KB_CATEGORY_ROBOT "Robot"
#define KB_CATEGORY_ADMIN "Admin"
